title: Mario Garingo
logo: /assets/img/logo.png
description: I use my knowledge in signal processing and machine learning techniques to solve various problems spanning from biological to audio and image applications
show_downloads: false
theme: jekyll-theme-minimal